<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>nemerle-language-server</AssemblyName>
    <RootNamespace>Nemerle.LanguageServer</RootNamespace>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <RollForward>LatestMajor</RollForward>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NemerleBin Condition="'$(NemerleBin)' == ''">$(MSBuildProjectDirectory)\..\..\..\boot-dnlib</NemerleBin>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Nemerle">
      <HintPath>$(NemerleBin)\Nemerle.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Nemerle.Compiler">
      <HintPath>$(NemerleBin)\Nemerle.Compiler.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Nemerle.Macros">
      <HintPath>$(NemerleBin)\Nemerle.Macros.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="dnlib">
      <HintPath>$(NemerleBin)\dnlib.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Nemerle.Language.Core">
      <HintPath>..\nemerle-language-core\bin\Release\Nemerle.Language.Core.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
</Project>
