name: CI

on:
  push:
    branches:
      - ftp
    tags:
      - v*
  pull_request:
jobs:
  build:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Setup VSWhere.exe
      uses: warrenbuckley/Setup-VSWhere@v1
    - name: Add MSBuild to PATH
      run: |
        $exe = vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        $dir = Split-Path $exe -Parent
        echo "::add-path::$dir"
    - name: Build
      run: msbuild NemerleAll.nproj /t:InstallerFull /tv:4.0 /p:TargetFrameworkVersion=v4.0;Configuration=Release
      shell: cmd
    - name: Remove wixpdb
      run: Remove-Item bin\Release\net-4.0\Installer\*.wixpdb
    - name: Upload artifacts to github build
      uses: actions/upload-artifact@v2
      with:
        name: SetupAndBinaries
        path: bin/Release/net-4.0/Installer
    - name: Upload artifacts to FTP
      run: |
        $Dir="bin/Release/net-4.0/Installer"
        $ftp = "${{ secrets.MASTER_FTP_PATH }}" 
        $user = "${{ secrets.FTP_LOGIN }}" 
        $pass = "${{ secrets.FTP_PASSWORD }}"  
        $webclient = New-Object System.Net.WebClient 
        $webclient.Credentials = New-Object System.Net.NetworkCredential($user,$pass)  
        foreach($item in (dir $Dir)){ 
            "Uploading $item..." 
            $uri = New-Object System.Uri($ftp+$item.Name) 
            $webclient.UploadFile($uri, $item.FullName) 
        }

